name: 'Radicati Events'
description: 'Adding for radicati site adding Event content type. Some requirements are not included here to maintain after the fact applying of this recipe.'
type: 'Content'
install:
  - field
  - field_ui
  - text
  - filter
  - editor
  - ckeditor5
  - text_field_formatter
  - smart_date
  - link
  - options
  - telephone
  - entity_reference_revisions
  - file
  - field_group
  - taxonomy
config:
  import:
    smart_date: "*"
